name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - jojo
      - jojo-test

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-18.04
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: "github.ref != 'refs/heads/master'"

  build:
    name: Build (Go ${{ matrix.go }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.15.2]
        # os: ["ubuntu-18.04", "macos-10.15"]
        os: ["ubuntu-18.04"]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - name: Build
        run: |
          go get ./cmd/...
          which goworld
          goworld build examples/nil_game
          mkdir -p downloads
          cp $(which goworld) ./downloads
          cp components/dispatcher ./downloads
          cp components/gate ./downloads
      - uses: actions/upload-artifact@v3
        with:
          name: goworld-${{ matrix.os }}
          path: ${{ github.workspace }}/downloads
